console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Javi Teaches trabajando");
console.log("Javi Teaches trabajando");
console.log("Javi Teaches trabajando");
