console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.info("Este es mi trabajo");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo working");
console.log("Japsolo continue working");
console.log("Japsolo continue working");
console.log("Japsolo continue working");
